### ISSUE TITLE
exception traceback with pyramid-debugtoolbar==2.0.2

### ISSUE THREAD

**Issue by tisdall** [Pylons/pyramid_debugtoolbar#145]
on a `GET /_debug_toolbar/31343xxxxxxxx38`:

```
Traceback (most recent call last):
  File "/sites/metrics_dev/env/lib/python3.3/site-packages/pyramid-1.4.5-py3.3.egg/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/sites/metrics_dev/env/lib/python3.3/site-packages/pyramid-1.4.5-py3.3.egg/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/sites/metrics_dev/env/lib/python3.3/site-packages/pyramid_debugtoolbar/toolbar.py", line 160, in toolbar_tween
    return handler(request)
  File "/sites/metrics_dev/env/lib/python3.3/site-packages/pyramid-1.4.5-py3.3.egg/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/sites/metrics_dev/env/lib/python3.3/site-packages/pyramid_tm-0.7-py3.3.egg/pyramid_tm/__init__.py", line 82, in tm_tween
    reraise(*exc_info)
  File "/sites/metrics_dev/env/lib/python3.3/site-packages/pyramid_tm-0.7-py3.3.egg/pyramid_tm/compat.py", line 13, in reraise
    raise value
  File "/sites/metrics_dev/env/lib/python3.3/site-packages/pyramid_tm-0.7-py3.3.egg/pyramid_tm/__init__.py", line 63, in tm_tween
    response = handler(request)
  File "/sites/metrics_dev/env/lib/python3.3/site-packages/pyramid-1.4.5-py3.3.egg/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/sites/metrics_dev/env/lib/python3.3/site-packages/pyramid-1.4.5-py3.3.egg/pyramid/config/views.py", line 237, in _secured_view
    return view(context, request)
  File "/sites/metrics_dev/env/lib/python3.3/site-packages/pyramid-1.4.5-py3.3.egg/pyramid/config/views.py", line 377, in viewresult_to_response
    result = view(context, request)
  File "/sites/metrics_dev/env/lib/python3.3/site-packages/pyramid-1.4.5-py3.3.egg/pyramid/wsgi.py", line 73, in decorator
    return call_app_with_subpath_as_path_info(request, wrapped)
  File "/sites/metrics_dev/env/lib/python3.3/site-packages/pyramid-1.4.5-py3.3.egg/pyramid/request.py", line 461, in call_app_with_subpath_as_path_info
    return new_request.get_response(app)
  File "/sites/metrics_dev/env/lib/python3.3/site-packages/WebOb-1.3.1-py3.3.egg/webob/request.py", line 1320, in send
  File "/sites/metrics_dev/env/lib/python3.3/site-packages/WebOb-1.3.1-py3.3.egg/webob/request.py", line 1284, in call_application
  File "/sites/metrics_dev/env/lib/python3.3/site-packages/pyramid-1.4.5-py3.3.egg/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/sites/metrics_dev/env/lib/python3.3/site-packages/pyramid-1.4.5-py3.3.egg/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/sites/metrics_dev/env/lib/python3.3/site-packages/pyramid-1.4.5-py3.3.egg/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/sites/metrics_dev/env/lib/python3.3/site-packages/pyramid-1.4.5-py3.3.egg/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/sites/metrics_dev/env/lib/python3.3/site-packages/pyramid-1.4.5-py3.3.egg/pyramid/config/views.py", line 377, in viewresult_to_response
    result = view(context, request)
  File "/sites/metrics_dev/env/lib/python3.3/site-packages/pyramid-1.4.5-py3.3.egg/pyramid/config/views.py", line 493, in _requestonly_view
    response = view(request)
  File "/sites/metrics_dev/env/lib/python3.3/site-packages/pyramid_debugtoolbar/views.py", line 264, in sse
    for _id,toolbar in history.last(10)]
  File "/sites/metrics_dev/env/lib/python3.3/site-packages/pyramid_debugtoolbar/views.py", line 264, in <listcomp>
    for _id,toolbar in history.last(10)]
  File "/sites/metrics_dev/env/lib/python3.3/site-packages/pyramid_debugtoolbar/toolbar.py", line 62, in json
    'path': self.request.path,
  File "/sites/metrics_dev/env/lib/python3.3/site-packages/WebOb-1.3.1-py3.3.egg/webob/request.py", line 486, in path
  File "/sites/metrics_dev/env/lib/python3.3/site-packages/WebOb-1.3.1-py3.3.egg/webob/descriptors.py", line 68, in fget
  File "/sites/metrics_dev/env/lib/python3.3/site-packages/WebOb-1.3.1-py3.3.egg/webob/request.py", line 159, in encget
KeyError: 'PATH_INFO'
```

pertinent entries from `pip freeze`:

```
pyramid==1.4.5
pyramid-debugtoolbar==2.0.2
pyramid-tm==0.7
WebOb==1.3.1
Mako==0.9.1
Pygments==1.6
repoze.lru==0.6
```

**Comment by lieryan** [comment]
Had same issue with:

```
pyramid==1.4.5
pyramid-debugtoolbar==2.1
```

I'm also running on uWSGI. When this issue happens, printing `self.environ` shows that it is an empty dictionary. Somehow, the environ dictionary of a historical requests is not populated, producing an invalid WSGI environ.

Further testing shows that this issue only happens in uWSGI in threaded mode; when switching to single-process, single-thread mode, the issue does not happen. So a workaround would be to switch to single-process, single-thread mode.

**Comment by mmerickel** [comment]
related https://github.com/Pylons/pyramid_debugtoolbar/issues/235
