### ISSUE TITLE
exception when trying "explain" on an sql query

### ISSUE THREAD

**Issue by tisdall** [Pylons/pyramid_debugtoolbar#167]
```
Traceback (most recent call last):
  File "/sites/metrics_dev/env/lib/python3.4/site-packages/pyramid-1.5-py3.4.egg/pyramid/router.py", line 242, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/sites/metrics_dev/env/lib/python3.4/site-packages/pyramid-1.5-py3.4.egg/pyramid/router.py", line 217, in invoke_subrequest
    response = handle_request(request)
  File "/sites/metrics_dev/env/lib/python3.4/site-packages/pyramid_debugtoolbar/toolbar.py", line 165, in toolbar_tween
    return handler(request)
  File "/sites/metrics_dev/env/lib/python3.4/site-packages/pyramid-1.5-py3.4.egg/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/sites/metrics_dev/env/lib/python3.4/site-packages/pyramid_tm-0.7-py3.4.egg/pyramid_tm/__init__.py", line 82, in tm_tween
    reraise(*exc_info)
  File "/sites/metrics_dev/env/lib/python3.4/site-packages/pyramid_tm-0.7-py3.4.egg/pyramid_tm/compat.py", line 13, in reraise
    raise value
  File "/sites/metrics_dev/env/lib/python3.4/site-packages/pyramid_tm-0.7-py3.4.egg/pyramid_tm/__init__.py", line 63, in tm_tween
    response = handler(request)
  File "/sites/metrics_dev/env/lib/python3.4/site-packages/pyramid-1.5-py3.4.egg/pyramid/router.py", line 163, in handle_request
    response = view_callable(context, request)
  File "/sites/metrics_dev/env/lib/python3.4/site-packages/pyramid-1.5-py3.4.egg/pyramid/config/views.py", line 385, in viewresult_to_response
    result = view(context, request)
  File "/sites/metrics_dev/env/lib/python3.4/site-packages/pyramid-1.5-py3.4.egg/pyramid/wsgi.py", line 73, in decorator
    return call_app_with_subpath_as_path_info(request, wrapped)
  File "/sites/metrics_dev/env/lib/python3.4/site-packages/pyramid-1.5-py3.4.egg/pyramid/request.py", line 311, in call_app_with_subpath_as_path_info
    return new_request.get_response(app)
  File "/sites/metrics_dev/env/lib/python3.4/site-packages/WebOb-1.4-py3.4.egg/webob/request.py", line 1320, in send
  File "/sites/metrics_dev/env/lib/python3.4/site-packages/WebOb-1.4-py3.4.egg/webob/request.py", line 1284, in call_application
  File "/sites/metrics_dev/env/lib/python3.4/site-packages/pyramid-1.5-py3.4.egg/pyramid/router.py", line 242, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/sites/metrics_dev/env/lib/python3.4/site-packages/pyramid-1.5-py3.4.egg/pyramid/router.py", line 217, in invoke_subrequest
    response = handle_request(request)
  File "/sites/metrics_dev/env/lib/python3.4/site-packages/pyramid-1.5-py3.4.egg/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/sites/metrics_dev/env/lib/python3.4/site-packages/pyramid-1.5-py3.4.egg/pyramid/router.py", line 163, in handle_request
    response = view_callable(context, request)
  File "/sites/metrics_dev/env/lib/python3.4/site-packages/pyramid-1.5-py3.4.egg/pyramid/config/views.py", line 329, in attr_view
    return view(context, request)
  File "/sites/metrics_dev/env/lib/python3.4/site-packages/pyramid-1.5-py3.4.egg/pyramid/config/views.py", line 305, in predicate_wrapper
    return view(context, request)        
  File "/sites/metrics_dev/env/lib/python3.4/site-packages/pyramid-1.5-py3.4.egg/pyramid/config/views.py", line 355, in rendered_view
    result = view(context, request)
  File "/sites/metrics_dev/env/lib/python3.4/site-packages/pyramid-1.5-py3.4.egg/pyramid/config/views.py", line 477, in _class_requestonly_view
    response = getattr(inst, attr)()
  File "/sites/metrics_dev/env/lib/python3.4/site-packages/pyramid_debugtoolbar/views.py", line 186, in sql_explain
    engines = self.request.registry.parent_registry.pdtb_sqla_engines
AttributeError: 'Registry' object has no attribute 'pdtb_sqla_engines'
```

I'm using the following:
```
SQLAlchemy==0.9.4
oursql==0.9.4
zope.sqlalchemy==0.7.4
pyramid-debugtoolbar==2.1
```

**Comment by mmerickel** [comment]
I'm unable to reproduce this example using the sqlalchemy features of the demo app in the repo.
