### ISSUE TITLE
Panel crashes with Unicode keys in POST

### ISSUE THREAD

**Issue by estatic** [Pylons/pyramid_debugtoolbar#184]
```python
Traceback (most recent call last):
  File "/home/grunev/Documents/workspace/python/usnews/env/local/lib/python2.7/site-packages/pyramid_mako-0.3.1-py2.7.egg/pyramid_mako/__init__.py", line 142, in __call__
    result = template.render_unicode(**system)
  File "/home/grunev/Documents/workspace/python/usnews/env/local/lib/python2.7/site-packages/Mako-0.9.0-py2.7.egg/mako/template.py", line 452, in render_unicode
    as_unicode=True)
  File "/home/grunev/Documents/workspace/python/usnews/env/local/lib/python2.7/site-packages/Mako-0.9.0-py2.7.egg/mako/runtime.py", line 807, in _render
    **_kwargs_for_callable(callable_, data))
  File "/home/grunev/Documents/workspace/python/usnews/env/local/lib/python2.7/site-packages/Mako-0.9.0-py2.7.egg/mako/runtime.py", line 839, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/home/grunev/Documents/workspace/python/usnews/env/local/lib/python2.7/site-packages/Mako-0.9.0-py2.7.egg/mako/runtime.py", line 865, in _exec_template
    callable_(context, *args, **kwargs)
  File "/home/grunev/Documents/workspace/python/usnews/env/local/lib/python2.7/site-packages/pyramid_debugtoolbar-1.0.9-py2.7.egg/pyramid_debugtoolbar/panels/templates/request_vars.dbtmako", line 87, in render_body
    <td>${key|h}</td>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 14: ordinal not in range(128)
```

So, can you please change in file
pyramid_debugtoolbar/panels/request_vars.py

Line 36
REMOVE 'post': [(k, [saferepr(p) for p in request.POST.getall(k)])
ADD 'post': [(k.decode('utf-8'), [saferepr(p) for p in request.POST.getall(k)])

**Comment by mmerickel** [comment]
Is this still an issue? This code has been through some iterations since this was opened.
