### ISSUE TITLE
debug toolbar doesn't support IPv6 link-local addresses

### ISSUE THREAD

**Issue by bertjwregeer** [Pylons/pyramid_debugtoolbar#265]
I'm adding support to waitress to serve on all IP's, including IPv6 and the remote client is connecting from

`fe80::aa20:66ff:fe3a:fa79%en0`

Which is a link-local address. This is not considered a valid IP address by the `ipaddr` library that is vendored with the debug toolbar.

Note, this is also considered invalid by the `ipaddress` library shipped with Python 3.5, so we are in good company.

```
2016-06-11 17:38:27,194 ERROR [waitress:341][waitress] Exception when serving /
Traceback (most recent call last):
  File "/Users/xistence/Projects/waitress/waitress/channel.py", line 338, in service
    task.service()
  File "/Users/xistence/Projects/waitress/waitress/task.py", line 169, in service
    self.execute()
  File "/Users/xistence/Projects/waitress/waitress/task.py", line 399, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/Users/xistence/.ve/fulgent/lib/python3.5/site-packages/pyramid/router.py", line 236, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/Users/xistence/.ve/fulgent/lib/python3.5/site-packages/pyramid/router.py", line 211, in invoke_subrequest
    response = handle_request(request)
  File "/Users/xistence/.ve/fulgent/lib/python3.5/site-packages/pyramid_debugtoolbar/toolbar.py", line 184, in toolbar_tween
    or not addr_in(last_proxy_addr, hosts)
  File "/Users/xistence/.ve/fulgent/lib/python3.5/site-packages/pyramid_debugtoolbar/utils.py", line 191, in addr_in
    if ipaddr.IPAddress(addr) in ipaddr.IPNetwork(host):
  File "/Users/xistence/.ve/fulgent/lib/python3.5/site-packages/pyramid_debugtoolbar/ipaddr.py", line 85, in IPAddress
    address)
ValueError: 'fe80::aa20:66ff:fe3a:fa79%en0' does not appear to be an IPv4 or IPv6 address
```

We should probably strip off the `%` and anything following it...

**Comment by bertjwregeer** [comment]
Related: https://github.com/Pylons/pyramid_debugtoolbar/issues/166
