### ISSUE TITLE
Bug in call to process_session_attr causing apps to fail

### ISSUE THREAD

**Issue by kashifpk** [Pylons/pyramid_debugtoolbar#267]
Current version and code at mast has an error which causes pyramid applications using pyramid_debugtoolbar not to run and give the error below:

`2016-07-02 04:25:20,390 ERROR [waitress][waitress] Exception when serving /favicon.ico
Traceback (most recent call last):                                                                                                           
  File "/MyWork/ElanceProjects/Threatify/venv/lib/python3.5/site-packages/waitress/channel.py", line 338, in service
    task.service()
  File "/MyWork/ElanceProjects/Threatify/venv/lib/python3.5/site-packages/waitress/task.py", line 169, in service
    self.execute()
  File "/MyWork/ElanceProjects/Threatify/venv/lib/python3.5/site-packages/waitress/task.py", line 399, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/MyWork/ElanceProjects/Threatify/venv/lib/python3.5/site-packages/pyramid/router.py", line 236, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/MyWork/ElanceProjects/Threatify/venv/lib/python3.5/site-packages/pyramid/router.py", line 211, in invoke_subrequest
    response = handle_request(request)
  File "/MyWork/ElanceProjects/Threatify/code/tf-backend/threatify_api/auth.py", line 92, in auth_request
    return handler(request)
  File "/MyWork/ElanceProjects/Threatify/venv/lib/python3.5/site-packages/pyramid_debugtoolbar/toolbar.py", line 201, in toolbar_tween
    default_active_panels)
  File "/MyWork/ElanceProjects/Threatify/venv/lib/python3.5/site-packages/pyramid_debugtoolbar/toolbar.py", line 66, in __init__
    panel_inst = panel_class(request)
  File "/MyWork/ElanceProjects/Threatify/venv/lib/python3.5/site-packages/pyramid_debugtoolbar/panels/request_vars.py", line 93, in __init__
    self.process_session_attr(self, attrs['session'])
TypeError: process_session_attr() takes 2 positional arguments but 3 were given`

The cause is just an erroneous self argument passed to the process_session_attr function.

**Comment by kashifpk** [comment]
Fixed here:
#https://github.com/Pylons/pyramid_debugtoolbar/pull/268
