### ISSUE TITLE
 No static URL definition matching pyramid_debugtoolbar:static/toolbar/toolbar_button.css

### ISSUE THREAD

**Issue by Kilte** [Pylons/pyramid_debugtoolbar#275]
Python version: 2.7.9
pyramid version: 1.7.3
pyramid_debugtoolbar version: 3.0.5

```
2016-11-21 17:27:30,047 ERROR [waitress][Dummy-2] Exception when serving /
Traceback (most recent call last):
  File "/home/kilte/projects/sample_project/eggs/waitress-0.8.5-py2.7.egg/waitress/channel.py", line 332, in service
    task.service()
  File "/home/kilte/projects/sample_project/eggs/waitress-0.8.5-py2.7.egg/waitress/task.py", line 174, in service
    self.execute()
  File "/home/kilte/projects/sample_project/eggs/waitress-0.8.5-py2.7.egg/waitress/task.py", line 382, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/home/kilte/projects/sample_project/eggs/PasteDeploy-1.5.0-py2.7.egg/paste/deploy/config.py", line 291, in __call__
    return self.app(environ, start_response)
  File "/home/kilte/projects/sample_project/eggs/pyramid-1.7.3-py2.7.egg/pyramid/router.py", line 236, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/kilte/projects/sample_project/eggs/pyramid-1.7.3-py2.7.egg/pyramid/router.py", line 211, in invoke_subrequest
    response = handle_request(request)
  File "/home/kilte/projects/sample_project/src/sample_project/lib/city.py", line 97, in UserCityMiddleware
    response = handler(request)
  File "/home/kilte/projects/sample_project/eggs/mo.i18n.pyramid-0.1.3-py2.7.egg/mo/i18n/pyramid/__init__.py", line 35, in set_locale_tween
    return handler(request)
  File "/home/kilte/projects/sample_project/eggs/mo.auth.pyramid-0.2.0-py2.7.egg/mo/auth/pyramid/tween.py", line 18, in sso_auth_tween
    return handler(request)
  File "/home/kilte/projects/sample_project/eggs/pyramid_debugtoolbar-3.0.5-py2.7.egg/pyramid_debugtoolbar/toolbar.py", line 280, in toolbar_tween
    toolbar.inject(request, response)
  File "/home/kilte/projects/sample_project/eggs/pyramid_debugtoolbar-3.0.5-py2.7.egg/pyramid_debugtoolbar/toolbar.py", line 101, in inject
    STATIC_PATH + 'toolbar/toolbar_button.css')
  File "/home/kilte/projects/sample_project/eggs/pyramid-1.7.3-py2.7.egg/pyramid/url.py", line 716, in static_url
    return info.generate(path, self, **kw)
  File "/home/kilte/projects/sample_project/eggs/mo.pyramid_extensions-0.3.1-py2.7.egg/mo/pyramid_extensions/static_url.py", line 16, in generate
    return super(StaticURLInfo, self).generate(path, request, **kw)
  File "/home/kilte/projects/sample_project/eggs/pyramid-1.7.3-py2.7.egg/pyramid/config/views.py", line 1820, in generate
    raise ValueError('No static URL definition matching %s' % path)
ValueError: No static URL definition matching pyramid_debugtoolbar:static/toolbar/toolbar_button.css
```

**Comment by Kilte** [comment]
My bad. I redefined IStaticURLInfo utility after including toolbar.
