### ISSUE TITLE
Error when running with pyramid-2.0 and pyramid_mako-1.0.2.

### ISSUE THREAD

**Issue by tysonliddell** [Pylons/pyramid_debugtoolbar#376]
## Issue
There appears to be an issue when using the latest `pyramid_debugtoolbar` with `pyramid-2.0` when `pyramid_mako-1.0.2` is selected by `pip` to resolve the dependencies, as happened for me when using my company's PyPI repo.

## To reproduce:
```
---------------
setup.py
---------------
from setuptools import setup

requires = [
    'pyramid==2.0',
    'pyramid_mako==1.0.2',
    'pyramid_debugtoolbar==4.9',
    'waitress==2.1.2',
]

setup(
  install_requires=requires,
)
```

```
---------------
app.py
---------------
from waitress import serve
from pyramid.config import Configurator

if __name__ == '__main__':
    with Configurator() as config:
        config.include('pyramid_debugtoolbar')
        app = config.make_wsgi_app()
    serve(app, host='0.0.0.0', port=6543)
```

Then running `pip install -e .` followed by `python app.py` results in the following traceback
```
Traceback (most recent call last):
  File "/Users/me/dev/pyramid/test.py", line 14, in <module>
    config.include('pyramid_debugtoolbar')
  File "/Users/me/dev/pyramid/env/lib/python3.9/site-packages/pyramid/config/__init__.py", line 666, in include
    c(configurator)
  File "/Users/me/dev/pyramid/env/lib/python3.9/site-packages/pyramid_debugtoolbar/__init__.py", line 126, in includeme
    application = make_toolbar_app(settings, config.registry)
  File "/Users/me/dev/pyramid/env/lib/python3.9/site-packages/pyramid_debugtoolbar/toolbar_app.py", line 44, in make_toolbar_app
    config.include('pyramid_mako')
  File "/Users/me/dev/pyramid/env/lib/python3.9/site-packages/pyramid/config/__init__.py", line 632, in include
    c = self.maybe_dotted(callable)
  File "/Users/me/dev/pyramid/env/lib/python3.9/site-packages/pyramid/config/__init__.py", line 740, in maybe_dotted
    return self.name_resolver.maybe_resolve(dotted)
  File "/Users/me/dev/pyramid/env/lib/python3.9/site-packages/pyramid/path.py", line 327, in maybe_resolve
    return self._resolve(dotted, package)
  File "/Users/me/dev/pyramid/env/lib/python3.9/site-packages/pyramid/path.py", line 334, in _resolve
    return self._zope_dottedname_style(dotted, package)
  File "/Users/me/dev/pyramid/env/lib/python3.9/site-packages/pyramid/path.py", line 383, in _zope_dottedname_style
    found = __import__(used)
  File "/Users/me/dev/pyramid/env/lib/python3.9/site-packages/pyramid_mako/__init__.py", line 11, in <module>
    from pyramid.compat import (
ModuleNotFoundError: No module named 'pyramid.compat'
```

It looks like`pyramid.compat` was removed by `pyramid-2.0`. I can confirm that the error does not occur if I bump to the next version of `pyramid_mako` as shown:

```diff
 requires = [
     'pyramid==2.0',
-   'pyramid_mako==1.0.2',
+   'pyramid_mako==1.1.0',
     'pyramid_debugtoolbar==4.9',
     'waitress==2.1.2',
 ]
```

**Comment by mmerickel** [comment]
The solution is to just upgrade to pyramid_mako 1.1.0+ which is compatible with pyramid 2.0.
